# Inspired from https://github.com/actions/starter-workflows/blob/main/pages/nextjs.yml
name: Build Docker Image

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
      
    outputs:
      new_version: ${{ steps.increment_version.outputs.new_version }}
      
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Read current version
        id: get_version
        run: |
          VERSION=$(cat .version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV


      - name: Increment version
        id: increment_version
        run: |
          VERSION=$(cat .version)
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$patch"
          echo "$NEW_VERSION" > .version
          echo "::set-output name=new_version::$NEW_VERSION"
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

          
      - name: Build Docker image
        run: |
          docker build -t moonhou/ifcat:${{ env.NEW_VERSION }} .
      
      - name: Save Docker image to tar file
        run: |
          docker save moonhou/ifcat:${{ env.NEW_VERSION }} -o ifcat-v${{ env.NEW_VERSION }}.tar
      
      - name: Commit and push version update
        uses: EndBug/add-and-commit@v9
        with:
          add: '.version'
          message: 'Bump version to ${{ env.NEW_VERSION }}'
          author_name: 'github-actions'
          author_email: 'github-actions@github.com'

      - name: Upload Docker image tar file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ifcat-v${{ env.NEW_VERSION }}.tar
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Docker image tar file
        uses: actions/download-artifact@v3
        with:
          name: docker-image
      - name: Debug NEW_VERSION in deploy job
        run: echo "Deploying version ${{ needs.build.outputs.new_version }}"

      - name: Install sshpass
        run: sudo apt-get install -y sshpass
      
      - name: SCP Docker image tar file to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          DEST_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          sshpass -p $SSH_PRIVATE_KEY scp ifcat-v${{ needs.build.outputs.new_version }}.tar $SERVER_USER@$SERVER_IP:$DEST_PATH/ifcat-v${{ needs.build.outputs.new_version }}.tar
